### PR TITLE
Able to run remotely via only script tag but unable to deploy to Vercel

### PR DESCRIPTION
**Pull request by ssu-carlsoni**
Summary of changes

- added 
  - README.md
  - .env.sample
  - .gitignore
- move all static files to ./static directory accessible via https://{backend_url}/static/filename
- move CSS from JS to a chatbot.css with all static assets relative urls
- chatbot.js
  - wrapped in IIFE to protect the global variable scope when used on external sites
  - moved x-author to variable backend_token
  - places CSS in JS with addCssLink to load static chatbot.css
  - some auto-formatting and update conditions to prevent possible type coercion
- api.py
  - added app.mount /static using fastapi.staticfiles to serve static files from the static directory
  - added allow_dangerous_deserialization to FAISS.load_local to stop security error
  - some auto-formatting and update conditions to prevent possible type coercion

### CODE REVIEW

**Comment by ssu-carlsoni** [comment]
I want to share the progress I've made in getting your project to remove locally by just adding a <script> tag to chatbot.js.  I can't get this to deploy to Vercel due to build size.  Vercel only allows the build size to be a max 250MB and faiss-cpu alone os 110MB.  I'm not sure you want to merge these changes until working on Vercel but I thought sharing my work might be helpful.

**Comment by Wasmahdi** [comment]
This sounds like a problem. I am going through the changes. I am trying to find a solution to this. I will let you know if I am able to solve it.

**Comment by ssu-carlsoni** [comment]
working to move these changes to the frontend project

**Comment by ssu-carlsoni** [comment]
Looks like my PR triggered this notification.  I've closed the and I'm
working on getting the changes just to the frontend.



Thank You,
Ian Carlson
Lead Web Developer
Sonoma State University, Information Technology
e: ***@***.***
o: 707-664-3570
m: 707-321-5586

**Pull request closed without merging**
